### ISSUE TITLE
Apple sbix tables are supported via @FontFace in Safari

### ISSUE THREAD

**Issue by schriftgestalt** [RoelN/ChromaCheck#26]
In MacOS since 10.10, Safari does show the sbix table from fonts loaded with @fontface. I put together a small sample page: [files.glyphsapp.com/test_page.html](http://files.glyphsapp.com/test_page.html) It should show a colourful 'C'.

The test page does say that sbix is not supported on Safari even through it is.

**Comment by RoelN** [comment]
Thanks for reporting! This is an old bug biting me in the butt again, I'll fix this a.s.a.p.!

**Comment by RoelN** [comment]
Well, that was even more anticlimactic than I expected: http://pixelambacht.nl/chromacheck wasn't using the latest JavaScript. It's updated now and should properly report sbix support in Safari!
