### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Jolg42** [RoelN/ChromaCheck#28]
Hi @RoelN 

It looks like your website is down…! https://pixelambacht.nl/chromacheck/
because your domain is in quarantine 😢  

In the meantime I forked your repo and made it available via GitHub Pages https://jolg42.github.io/ChromaCheck/demo.html 😉

**Comment by RoelN** [comment]
Thanks for reporting, Joël! The domain has been claimed back so I hope to see it all working again soon.

Many thanks for setting up the mirror!!

**Comment by Jolg42** [comment]
Many thanks to you for the repositories, fonts & blog posts! 👍

It looks like it's working again from here: https://pixelambacht.nl/chromacheck/ That was quick!
