### ISSUE TITLE
Win10 Edge passes ChromaCheck but actual visual check shows it is really buggy

### ISSUE THREAD

**Issue by yincrash** [RoelN/ChromaCheck#30]
TTF CBDT font fails (tested using NotoColorEmoji.ttf).
Converted to woff, it shows up: https://rawgit.com/yincrash/43341c4848949b0e6534277cfe70d950/raw/07e192c9f2e646413a099b41181b6cc43e772c53/cbdt-test.html

However, loading that one CBDT font meant CBDT fonts following it failed to render. On that test page, I also included your ChromaCheck CBDT font.

Additionally, CBDT font prevented a COLR font following it to not render:
https://rawgit.com/yincrash/43341c4848949b0e6534277cfe70d950/raw/07e192c9f2e646413a099b41181b6cc43e772c53/cbdt-test-no-emoji.html

This also means any regular windows 10 emoji fallback to a b&w version as seen here: https://rawgit.com/yincrash/43341c4848949b0e6534277cfe70d950/raw/07e192c9f2e646413a099b41181b6cc43e772c53/cbdt-test-only-cbdt.html

And just to make sure COLR fonts load properly, a control using the ChromaCheck COLR font:
https://rawgit.com/yincrash/43341c4848949b0e6534277cfe70d950/raw/07e192c9f2e646413a099b41181b6cc43e772c53/cbdt-test-only-colr.html

Maybe it would be worthwhile to implement a visual inspection on the ChromaCheck page in addition to the automated SVG check? Yet the https://pixelambacht.nl/chromacheck/old/ works fine! So maybe I'm just going crazy.

**Comment by RoelN** [comment]
Thanks for reporting! Creating a visual check would indeed be helpful, I kinda started missing it myself after deprecating the old test.

I see none of the ChromaCheck glyphs in your first link — they're both empty when I follow the link in Edge in Windows 10 preview. I get glyph-missing boxes in Android (where I'd expect CBDT to show up).

The second link does work as you describe, so there's definitely something going on there.

I patched the CBDT font yesterday, did you use the newest version?

**Comment by yincrash** [comment]
The ChromaCheck glyphs don't show up in the first link because the first `@font-face` declaration is for the noto emoji woff which is a CBDT font, so the fonts following it do not render. :( The order of the characters do not matter, just the declarations.

I did use the newest version. I decided to test this out after seeing your comment about the SVGinOT mailing list thread.

**Comment by RoelN** [comment]
Well, this was an interesting bug chase! It seems the problem is not with the fonts or OpenType, but with the CSS you used. The problem is here:

`@font-face { ... };`

That semicolon is not allowed after a `@font-face` declaration, and causes a parse error in Edge (and IE), ignoring all the following CSS. Chrome tolerates the semicolons and renders correctly. If you remove the semicolons, your tests will work :)

**Comment by yincrash** [comment]
Apologies! I was really worried it would be something stupid on my end. It's good to hear that it isn't just crazy IE font bugs.

**Comment by RoelN** [comment]
In this case, it's a matter of IE and Edge following spec precisely — not bad!
