### ISSUE TITLE
Firefox supports all four formats, shows as supporting only two

### ISSUE THREAD

**Issue by DeeDeeG** [RoelN/ChromaCheck#34]
Hi, I don't know a lot of the technical details here, but on my Linux machine I have copied Apple Color Emoji (which definitely worked) and I believe Segoe UI Emoji (not sure if I'm misremembering, have to try again). Firefox supported SVG in Opentype first, and will support the Google/Noto format without any major issues in Firefox 44 or 45.

So basically as I said in the title, Firefox can show all four formats, in full color and everything.

I feel like Firefox's wide emoji support isn't widely known. If you need me to test this more, or help make this more reproducible/debuggable, I'm interested in contributing some time toward that. It'd be nice to have a definitive resource such as this to test emoji support. Just needs to be updated a bit, I think!

**Comment by RoelN** [comment]
Thanks for reporting! There is a difference between support for fonts that are locally installed, and fonts loaded through `@font-face`. Chromacheck checks for the latter.

Could you check what [the old testpage](https://pixelambacht.nl/demo/color-font-test.html) does on your system?

**Comment by DeeDeeG** [comment]
> Could you check what the old testpage does on your system?

Sure. Here it is:

![color-font-test](https://cloud.githubusercontent.com/assets/20157115/26320508/02e0b5da-3ef1-11e7-84c4-d0fb0aa5629e.png)

**Comment by DeeDeeG** [comment]
On another note, chromium shows up more gray, but otherwise similar.

[color-font-test chromium.png](https://cloud.githubusercontent.com/assets/20157115/26321054/523772c0-3ef3-11e7-92ad-f19113ba7178.png)

[chromacheck chromium.png](https://cloud.githubusercontent.com/assets/20157115/26321055/5238d188-3ef3-11e7-8d63-95cb811c1db0.png)

**Comment by RoelN** [comment]
Yeah, that looks about right. CBDT and sbix won't work when loaded through `@font-face` in Firefox.

Nice to see CBDT supported in Chromium, though!

All in all it looks like Chromacheck is properly reporting support, so I'm closing this issue. I'll update the readme though so it's clear this is for `@font-face` fonts only.

**Comment by DeeDeeG** [comment]
This bug is closed, but I had a tiny update:

- Firefox can support CBDT/CBLC in `@font-face`... but only so with a flag enabled. (And it's disabled by default). Per [bug 1418818](https://bugzilla.mozilla.org/show_bug.cgi?id=1418818)
  - `gfx.downloadable_fonts.keep_color_bitmaps` = `true`

And for completeness' sake: Firefox still does not support sbix in `@font-face`. Per [bug 1422351](https://bugzilla.mozilla.org/show_bug.cgi?id=1422351)

**Comment by DeeDeeG** [comment]
And Firefox with the pref turned on shows as not supporting CBDT/CBLC on Chromacheck:

![Firefox visiting ChromaCheck, showing COLR and SVG-in-OpenType supported, but SBIX and CBDT/CBLC not supported](https://user-images.githubusercontent.com/20157115/49099600-e09c4800-f23f-11e8-9139-2b50f6528fd8.png)

I'm fairly certain Firefox support for CBDT/CBLC is working from my own tests. 

(Tested with my WIP project from a while ago: https://github.com/DeeDeeG/color-font-test)

**Comment by RoelN** [comment]
Thanks for reporting! That's interesting. There are several bugs surrounding CBDT/CBLC (the draft/final spec that (dis)allowed a `glyf` table, OTS rejecting fonts based on the draft spec, etc.) so I'd have to dig in and see what's going on here. Thanks for the tip about the flag!
