### ISSUE TITLE
README.md: Is the Firefox bug fixed yet?

### ISSUE THREAD

**Issue by DeeDeeG** [RoelN/ChromaCheck#35]
Hi.

In `README.md` it says this:

> Firefox (on OSX?) has a bug that prevents color glyphs from being used on canvas with fillText(). This has been fixed for locally installed fonts but *[**still needs more fixin'**](https://bugzilla.mozilla.org/show_bug.cgi?id=1237640)* for fonts loaded through `@font-face`. ChromaTest works around this by sticking the font in an SVG image, and then drawing that image on canvas.

It says the status is `Resolved:Fixed` over at [bugzilla.mozilla.org]([bug 1237640](https://bugzilla.mozilla.org/show_bug.cgi?id=1237640)), but it says it needs fixing in your README.md.

I am pretty sure ChromaCheck is 100% accurate, but every time I see that in the README I feel like I missed something and can't be sure anymore. Some clarity would be helpful. ChromaCheck working 100% has some impact on whether I put in the effort to maintain my own testing setup for color font support.

P.S. Incidentally: a minor typo in that sentence: 
> _**ChromaTest**_ works around this by . . .

**Comment by RoelN** [comment]
Good call, thanks for reporting! Will pick this up a.s.a.p.

**Comment by RoelN** [comment]
And a.s.a.p. turned out to be today! \o/
