### ISSUE TITLE
website is broken fix it, script on github works fine

### ISSUE THREAD

**Issue by cyan-2048** [RoelN/ChromaCheck#43]
Uncaught SyntaxError: identifier starts immediately after numeric literal chromacheck-min.js:6:5505

i only tested the unminified version on github

**Comment by anthrotype** [comment]
not sure if related, but whenever I load https://pixelambacht.nl/chromacheck/ in either Chrome, FF or Safari (on latest macOS), for _all_ the color font formats it says "**not** supported", which is unrealistic.

**Comment by bramus** [comment]
@anthrotype Yes, that's exactly the cause. I've tried pinging @RoelN on Twitter about this, but to no avail :(

**Comment by bramus** [comment]
Website up and running again _([ref](https://twitter.com/PixelAmbacht/status/1485886602098393100))_. This issue may be closed.

**Comment by RoelN** [comment]
I computered something wrong. Apologies for the broken ChromaCheck, and the hefty delay in fixing!
